services:
  ipa:
    image: freeipa/freeipa-server:rocky-9
    container_name: ipa
    hostname: ipa.example.local
    restart: always
    volumes:
      - data:/data
    environment:
      PASSWORD: passw0rd
      IPA_SERVER_IP: 172.28.0.10
    # command: ipa-server-install -U --domain='example.local' --realm='EXAMPLE.LOCAL' --netbios-name=EXAMPLE --no-ntp --setup-dns --forwarder='127.0.0.11' --forward-policy=only
    command: ipa-server-install -U -r EXAMPLE.LOCAL --no-ntp
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      # - "53:53"
      # - "88:88"
      # - "464:464"
      # - "88:88/udp"
      # - "53:53/udp"
      # - "464:464/udp"
    networks:
      ipa:
        ipv4_address: 172.28.0.10
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    tty: true
    stdin_open: true
      
networks:
  ipa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  data:
